<p>本js由KIPI-C制作</p>
        <p>
        <h3>下载地址：</h3>
        <a href="https://github.com/KIPI-C/k-audio.js" title="https://github.com/KIPI-C/k-audio.js">
        https://github.com/<wbr>KIPI-C/k-audio.js
        </a>
        </p>
        <p>另外还有其他作品的下载地址：
        <p>歌词读取引擎（k-lrcreader）：
        <a href="https://github.com/KIPI-C/k-lrcreader" title="https://github.com/KIPI-C/k-lrcreader">
        https://github.com/<wbr>KIPI-C/k-lrcreader引擎
        </a>
        </p>
        </p>
        <p>关注一下，随时更新！！</p>
